index:
  path: /
  controller: App\Controller\IndexController::index

dailyNoteIndex:
  path: /dailyNote
  controller: App\Controller\DailyHelperController::TodoHandler

createNewNote:
  path: /newNote
  controller: App\Controller\DailyHelperController::TodoHandler


createNew:
  path: /dailyNote/new
  controller: App\Controller\DailyHelperController::Handler

