index:
  path: /
  controller: App\Controller\IndexController::index

dailyNoteIndex:
  path: /dailyNote
  controller: App\Controller\DailyHelperController::TodoHandler

createNew:
  path: /dailyNote/new/{name}
  controller: App\Controller\DailyHelperController::Handler

todo:
  path: /todo/list
  controller: App\Controller\DailyHelperController::listOfTodo

habit:
  path: /habit
  controller: App\Controller\HabitController::index

newHabit:
  path: /habit/new
  controller: App\Controller\HabitController::handler

newCompletedHabits:
  path: /hb/{year}/{month}/{day}
  controller: App\Controller\HabitTrackerController::index

bookIndex:
  path: /book
  controller: App\Controller\BookController::index

bookPage:
  path: /bookPage/{id}
  controller: App\Controller\BookController::bookPage

newBook:
  path: /book/new
  controller: App\Controller\BookController::handler

editBook:
  path: /book/edit/{id}
  controller: App\Controller\BookController::handler
  
newBookTag:
  path: /bookTag/new
  controller: App\Controller\BookTagController::handler

calendar:
  path: /calendar
  controller: App\Controller\CalendarController::index
