index:
  path: /
  controller: App\Controller\IndexController::index

dailyNoteIndex:
  path: /dailyNote
  controller: App\Controller\DailyHelperController::TodoHandler

createNew:
  path: /dailyNote/new/{name}
  controller: App\Controller\DailyHelperController::Handler

todo:
  path: /todo/list
  controller: App\Controller\DailyHelperController::listOfTodo

habit:
  path: /habit
  controller: App\Controller\HabitController::index

newHabit:
  path: /habit/new
  controller: App\Controller\HabitController::handler

hb:
  path: /hb/{year}/{month}/{day}
  controller: App\Controller\HabitTrackerController::index